name: Node.js CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
 
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      # Step 3: Build Node.js image
      - name: Build Node.js image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true   # ✅ makes image available locally
          tags: my-node-app:latest
 
      # Step 4: Run Node.js container (host network)
      - name: Run Node.js container
        uses: addnab/docker-run-action@v3
        with:
          image: my-node-app:latest
          options: --network host
          run: |
            echo "✅ Node.js container started"
 
      # Step 5: Wait for Node.js app to be ready
      - name: Wait for Node.js
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "✅ Node.js app is up!"
              exit 0
            fi
            echo "Waiting for Node.js..."
            sleep 2
          done
          echo "❌ Node.js app did not start in time"
          exit 1
