name: Node.js CI
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
 
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      # Step 3: Build Node.js image
      - name: Build Node.js image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true   # ✅ makes image available locally
          tags: my-node-app:latest
 
      # Step 4: Run Node.js container (host network)
      - name: Run Node.js container
        uses: addnab/docker-run-action@v3
        with:
          image: my-node-app:latest
          options: --network host
          run: |
            echo "✅ Node.js container started"
 
